# Generated by Django 3.1.4 on 2020-12-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kakao_id', models.IntegerField(unique=True)),
                ('g_school_nickname', models.CharField(default='', max_length=3)),
                ('kakao_nickname', models.CharField(default='', max_length=20)),
                ('profile_image', models.CharField(default='', max_length=20)),
                ('is_manager', models.BooleanField(default=False)),
            ],
        ),
    ]
