# Generated by Django 3.1.4 on 2021-02-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saebyuk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lovebook',
            name='loved',
            field=models.BooleanField(default=False),
        ),
    ]
