# Generated by Django 3.1.4 on 2020-12-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saebyuk', '0003_auto_20201226_0251'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecommendedBook',
        ),
        migrations.AddField(
            model_name='book',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
    ]
