# Generated by Django 3.1.4 on 2020-12-26 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saebyuk', '0004_auto_20201226_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='is_recommended',
        ),
        migrations.CreateModel(
            name='RecommendedBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_recommended', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='recommended_book', to='saebyuk.book')),
            ],
            options={
                'db_table': 'recommended_book',
            },
        ),
    ]
