# Generated by Django 3.1.4 on 2020-12-25 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.IntegerField(unique=True)),
                ('registered_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'book',
                'ordering': ['isbn'],
            },
        ),
        migrations.CreateModel(
            name='RecommendedBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('book_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_query_name='book', serialize=False, to='saebyuk.book')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=30)),
                ('thumbnail_image', models.CharField(max_length=200)),
                ('publisher', models.CharField(max_length=25)),
                ('page', models.IntegerField()),
                ('published_date', models.DateTimeField()),
                ('keyword', models.CharField(max_length=30)),
                ('subtitle', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=100)),
                ('purchase_link', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'book_info',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kakao_id', models.IntegerField(unique=True)),
                ('g_school_nickname', models.CharField(default='', max_length=3)),
                ('kakao_nickname', models.CharField(default='', max_length=20)),
                ('profile_image', models.CharField(default='', max_length=200)),
                ('is_manager', models.BooleanField(default=False)),
                ('love_book', models.ManyToManyField(related_query_name='loved_book', to='saebyuk.Book')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['kakao_id'],
            },
        ),
        migrations.CreateModel(
            name='RequestedBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=25)),
                ('author', models.CharField(max_length=25)),
                ('interest_parts', models.CharField(max_length=25)),
                ('others', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='requested_user', to='saebyuk.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='BorrowBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_at', models.DateTimeField()),
                ('returned_at', models.DateTimeField(null=True)),
                ('is_overdue', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='book', to='saebyuk.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='borrower', to='saebyuk.usermodel')),
            ],
            options={
                'db_table': 'book_present_condition',
            },
        ),
        migrations.CreateModel(
            name='BookComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(max_length=20)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='book', to='saebyuk.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='commenter', to='saebyuk.usermodel')),
            ],
            options={
                'db_table': 'book_comment',
            },
        ),
    ]
