# Generated by Django 3.1.4 on 2021-02-06 06:11

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(default='', max_length=20, unique=True)),
                ('registered_date', models.DateTimeField(auto_now=True)),
                ('borrow_available', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'book',
                'ordering': ['isbn'],
            },
        ),
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=30)),
                ('thumbnail_image', models.CharField(max_length=200)),
                ('publisher', models.CharField(max_length=25)),
                ('page', models.IntegerField()),
                ('published_date', models.CharField(max_length=20)),
                ('genre', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=30), size=None)),
                ('keyword', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), size=None)),
                ('subtitle', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=1000)),
                ('purchase_link', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'book_info',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kakao_id', models.IntegerField(unique=True)),
                ('g_school_nickname', models.CharField(default='', max_length=3)),
                ('kakao_nickname', models.CharField(default='', max_length=20)),
                ('profile_image', models.CharField(default='', max_length=200)),
                ('is_manager', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['kakao_id'],
            },
        ),
        migrations.CreateModel(
            name='RequestedBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=25)),
                ('author', models.CharField(max_length=25)),
                ('interest_parts', models.CharField(max_length=25)),
                ('others', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='requested_user', to='saebyuk.usermodel')),
            ],
            options={
                'db_table': 'requested_book',
            },
        ),
        migrations.CreateModel(
            name='LoveBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='loved_book', to='saebyuk.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='lover', to='saebyuk.usermodel')),
            ],
            options={
                'db_table': 'book_loved',
            },
        ),
        migrations.CreateModel(
            name='BorrowBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_at', models.DateTimeField(auto_now_add=True)),
                ('returned_at', models.DateTimeField(null=True)),
                ('is_overdue', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='book', to='saebyuk.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='borrower', to='saebyuk.usermodel')),
            ],
            options={
                'db_table': 'book_present_condition',
            },
        ),
        migrations.CreateModel(
            name='BookComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(max_length=20)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='book', to='saebyuk.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='commenter', to='saebyuk.usermodel')),
            ],
            options={
                'db_table': 'book_comment',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='book_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_query_name='book_info', to='saebyuk.bookinfo'),
        ),
    ]
