# Generated by Django 3.1.4 on 2021-01-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saebyuk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='published_date',
            field=models.CharField(max_length=20),
        ),
    ]
