# Generated by Django 3.1.4 on 2021-02-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saebyuk', '0003_auto_20210129_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='borrow_available',
            field=models.BooleanField(default=True),
        ),
    ]
