# Generated by Django 3.1.4 on 2020-12-28 01:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saebyuk', '0006_auto_20201227_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedbook',
            name='able_to_borrow',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='keyword',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), size=None),
        ),
        migrations.AlterModelTable(
            name='requestedbook',
            table='requested_book',
        ),
    ]
