# Generated by Django 3.1.4 on 2020-12-28 02:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saebyuk', '0007_auto_20201228_0121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendedbook',
            name='able_to_borrow',
        ),
        migrations.RemoveField(
            model_name='recommendedbook',
            name='book',
        ),
        migrations.RemoveField(
            model_name='recommendedbook',
            name='is_recommended',
        ),
        migrations.AddField(
            model_name='recommendedbook',
            name='isbns',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
        ),
    ]
